#!/usr/bin/env node
// Generate host packaging from one portable manifest. --check never writes.
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const { $schema, ...metadata } = JSON.parse(readFileSync(join(root, 'plugin.json'), 'utf8'));
const codex = {
  ...metadata,
  skills: './skills/',
  interface: {
    displayName: 'Turma',
    shortDescription: 'Plan projects and ship grounded GitHub tickets',
    longDescription: metadata.description,
    developerName: metadata.author.name,
    category: 'Productivity',
    capabilities: ['Read', 'Write'],
    defaultPrompt: ['Use Turma to plan this project.'],
  },
};
const registry = JSON.parse(readFileSync(join(root, 'catalog/registry.json'), 'utf8'));
registry.catalogVersion = metadata.version;
const outputs = [
  // With the marketplace's root source (./), explicit skills replace Claude's
  // default skills scan. The wrappers retain Claude's explicit-only frontmatter.
  ['.claude-plugin/plugin.json', { ...metadata, skills: './claude-skills/' }],
  ['.codex-plugin/plugin.json', codex],
  ['catalog/registry.json', registry],
].map(([path, value]) => [path, JSON.stringify(value, null, 2) + '\n']);

for (const entry of readdirSync(join(root, 'skills'), { withFileTypes: true })) {
  if (!entry.isDirectory()) continue;
  const source = readFileSync(join(root, 'skills', entry.name, 'SKILL.md'), 'utf8');
  const frontmatter = source.match(/^---\n([\s\S]*?)\n---/)[1];
  // Existing workflows remain explicit-only; a skill can opt into normal discovery.
  const explicitOnly = !/^  invocation: automatic$/m.test(frontmatter);
  outputs.push([
    `claude-skills/${entry.name}/SKILL.md`,
    `---\n${frontmatter}\ndisable-model-invocation: ${explicitOnly}\n---\n\n` +
    `<!-- Generated by scripts/build-plugin.mjs. Edit skills/${entry.name}/SKILL.md. -->\n\n` +
    `Read and follow [the shared ${entry.name} workflow](../../skills/${entry.name}/SKILL.md).\n` +
    'Resolve its resource links relative to that shared file. The user\'s arguments\n' +
    'and existing authorization apply to that workflow.\n',
  ]);
  outputs.push([
    `skills/${entry.name}/agents/openai.yaml`,
    `# Generated by scripts/build-plugin.mjs.\ninterface:\n` +
    `  display_name: "Turma ${entry.name}"\n` +
    `  short_description: "Run Turma's ${entry.name} project workflow"\n` +
    `policy:\n  allow_implicit_invocation: ${!explicitOnly}\n`,
  ]);
}

let stale = false;
for (const [path, expected] of outputs) {
  const full = join(root, path);
  if (existsSync(full) && readFileSync(full, 'utf8') === expected) continue;
  if (process.argv.includes('--check')) {
    console.error(`${path} is stale; run node scripts/build-plugin.mjs`);
    stale = true;
  } else {
    mkdirSync(dirname(full), { recursive: true });
    writeFileSync(full, expected);
    console.log(`Generated ${path}`);
  }
}
if (stale) process.exitCode = 1;
